//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emp_CRUD_DbFirst.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Emp_Details
    {
        public int Emp_ID { get; set; }

        [Required]
        [MaxLength(50)]
        [Display(Name = "Employee Name")]
        public string Emp_Name { get; set; }

        [Required]
        [RegularExpression(@"^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$", ErrorMessage = "Invalid Email Address.")]
        [Display(Name = "Employee Email ID")]
        public string Emp_Email_ID { get; set; }

        [Required(ErrorMessage = "You must provide a Contact No")]
        [Display(Name = "Contact No")]
        [DataType(DataType.PhoneNumber)]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$", ErrorMessage = "Not a valid Contact No")]
        public string Emp_Contact_No { get; set; }

        [Required]
        [Display(Name = "Employee Salary")]
        public Nullable<int> Emp_Salary { get; set; }

        [Required]
        [MaxLength(50)]
        [Display(Name = "Employee City")]
        public string Emp_City { get; set; }
    }
}
